=== codejie/FlowEngine/src/definitions/schema/flow_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/codejie/flowengine/node_schema.json",
    "title": "Flow Definition",
    "description": "The Flow definition schema",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "nodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "index": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "parameters": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "[string | number | boolean | object | array | null]"
                                }               
                            },
                            "required": ["name", "value"]
                        }
                    },
                    "actions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "nextNodes": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                }
                            }
                        }
                    }
                },
                "required": ["index", "id"]
            }
        }
    },
    "required": ["id"]
}

=== codejie/FlowEngine/src/definitions/flows/test.json
{
    "id": "FLOW_TEST",
    "name": "TestFlow",
    "description": "the flow for testing",
    "nodes": [
        {
            "index": 1,
            "id": "NODE_START",
            "actions": [
                {
                    "id": "ACTION_AUTO",
                    "nextNodes": [
                        2
                    ]
                }
            ]
        },
        {
            "index": 2,
            "id": "NODE_END"
        }
    ]
}

=== codejie/FlowEngine/src/definitions/flows/min.json
{
    "id": "FLOW_TEST",
    "name": "TestFlow",
    "description": "START->AUTO->END:the minium flow for testing",
    "nodes": [
        {
            "index": 1,
            "id": "NODE_START",
            "actions": [
                {
                    "id": "ACTION_AUTO",
                    "nextNodes": [
                        3
                    ]
                }
            ]
        },
        {
            "index": 2,
            "id": "NODE_END"
        },
        {
            "index": 3,
            "id": "NODE_AUTO",
            "actions": [
                {
                    "id": "ACTION_AUTO",
                    "nextNodes": [
                        2
                    ]
                }
            ]
        }
    ]
}

=== codejie/FlowEngine/src/definitions/flows/input.json
{
    "id": "FLOW_INPUT",
    "name": "InputFlow",
    "description": "START->INPUT->END:the flow with input node",
    "nodes": [
        {
            "index": 1,
            "id": "NODE_START",
            "actions": [
                {
                    "id": "ACTION_AUTO",
                    "nextNodes": [
                        3
                    ]
                }
            ]
        },
        {
            "index": 2,
            "id": "NODE_END"
        },
        {
            "index": 3,
            "id": "NODE_INPUT",
            "actions": [
                {
                    "id": "ACTION_OK",
                    "nextNodes": [
                        2
                    ]
                }
            ]
        }
    ]
}
